language: node_js
node_js:
  - "0.10"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0081418be7250b9b9858
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false